// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC6JD829c2K5zfmDpRovsnG3XjTySsvncg',
    appId: '1:510169238122:web:72639eafd4e619cd17d813',
    messagingSenderId: '510169238122',
    projectId: 'ecommerceapp-2c3fa',
    authDomain: 'ecommerceapp-2c3fa.firebaseapp.com',
    storageBucket: 'ecommerceapp-2c3fa.appspot.com',
    measurementId: 'G-EQ2YL7TVBG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAKpPf4SRfQNC-gWbRkrrPU33WmooctD0o',
    appId: '1:510169238122:android:0052f07dc90e4d5d17d813',
    messagingSenderId: '510169238122',
    projectId: 'ecommerceapp-2c3fa',
    storageBucket: 'ecommerceapp-2c3fa.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBogKkdJp2ND8gL1REB9GcdRIdHu18E7Ws',
    appId: '1:510169238122:ios:6126afb2b15164b417d813',
    messagingSenderId: '510169238122',
    projectId: 'ecommerceapp-2c3fa',
    storageBucket: 'ecommerceapp-2c3fa.appspot.com',
    iosClientId: '510169238122-v1qps13k4kduu0jpqqt38ochmj23mlfc.apps.googleusercontent.com',
    iosBundleId: 'com.example.ecomUserApp',
  );
}
